export const demoPresets = {
  // ── DARK ──────────────────────────────────────────────
  midnight: {
    mode: "dark",
    storeName: "Noir Studio",
    tagline: "Bold. Dark. Unapologetically modern.",
    primaryColor: "#6366F1",
    secondaryColor: "#A78BFA",
    accentColor: "#4F46E5",
    bgPrimary: "#0F0F13",
    bgSecondary: "#18181F",
    surfaceColor: "#1E1E28",
    surfaceSoftColor: "#25252F",
    navbarBackground: "#0A0A0F",
    footerBackground: "#0A0A0F",
    headingColor: "#F1F0FF",
    bodyTextColor: "#C4C4D4",
    mutedTextColor: "#7C7C9A",
    textLightColor: "#FFFFFF",
    borderColor: "#2E2E3E",
    successColor: "#34D399",
    warningColor: "#FBBF24",
    dangerColor: "#F87171",
    infoColor: "#60A5FA",
    heroTitle: "Premium dark-mode storefront",
    heroSubtitle: "Sleek, immersive, and built for high-end brands.",
  },
  neon: {
    mode: "dark",
    storeName: "Pulse Drop",
    tagline: "Fast. Loud. Built for the next generation.",
    primaryColor: "#00F5A0",
    secondaryColor: "#00D9F5",
    accentColor: "#7B2FFF",
    bgPrimary: "#080C14",
    bgSecondary: "#0D1220",
    surfaceColor: "#111827",
    surfaceSoftColor: "#161E2E",
    navbarBackground: "#050810",
    footerBackground: "#050810",
    headingColor: "#E8FFF8",
    bodyTextColor: "#A8C4B8",
    mutedTextColor: "#5A7A6E",
    textLightColor: "#FFFFFF",
    borderColor: "#1A2E28",
    successColor: "#00F5A0",
    warningColor: "#FFD60A",
    dangerColor: "#FF4D6D",
    infoColor: "#00D9F5",
    heroTitle: "Next-gen streetwear & tech drops",
    heroSubtitle: "Limited drops. Unlimited hype. Shop before it's gone.",
  },
  obsidian: {
    mode: "dark",
    storeName: "Obsidian",
    tagline: "Sharp edges. Refined taste. Zero compromise.",
    primaryColor: "#E11D48",
    secondaryColor: "#FB7185",
    accentColor: "#BE123C",
    bgPrimary: "#0C0C0C",
    bgSecondary: "#141414",
    surfaceColor: "#1A1A1A",
    surfaceSoftColor: "#202020",
    navbarBackground: "#080808",
    footerBackground: "#080808",
    headingColor: "#F9FAFB",
    bodyTextColor: "#D1D5DB",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#262626",
    successColor: "#34D399",
    warningColor: "#FBBF24",
    dangerColor: "#F87171",
    infoColor: "#60A5FA",
    heroTitle: "Dark luxury with a bold red accent",
    heroSubtitle: "For brands that demand attention and command respect.",
  },
  // ── LIGHT ─────────────────────────────────────────────
  ivory: {
    mode: "light",
    storeName: "Blanc Maison",
    tagline: "Pure simplicity. Refined living.",
    primaryColor: "#1A1A1A",
    secondaryColor: "#C9A96E",
    accentColor: "#333333",
    bgPrimary: "#FAFAFA",
    bgSecondary: "#F4F4F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F8F8",
    navbarBackground: "#111111",
    footerBackground: "#0A0A0A",
    headingColor: "#111111",
    bodyTextColor: "#333333",
    mutedTextColor: "#888888",
    textLightColor: "#FFFFFF",
    borderColor: "#E5E5E5",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Luxury home & lifestyle essentials",
    heroSubtitle: "Curated for those who appreciate the beauty of simplicity.",
  },
  fashion: {
    mode: "light",
    storeName: "Maison Atelier",
    tagline: "Editorial fashion pieces for modern wardrobes.",
    primaryColor: "#7B3F61",
    secondaryColor: "#E9C46A",
    accentColor: "#1F1F1F",
    bgPrimary: "#F7F1F4",
    bgSecondary: "#F5E8EB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F4EDF0",
    navbarBackground: "#1F1F1F",
    footerBackground: "#111111",
    headingColor: "#1F1F1F",
    bodyTextColor: "#3A3A3A",
    mutedTextColor: "#716070",
    textLightColor: "#FFFFFF",
    borderColor: "#D8C2CF",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Client-ready fashion storefront",
    heroSubtitle: "Elegant storytelling, curated arrivals, and a premium checkout flow.",
  },
  electronics: {
    mode: "light",
    storeName: "Volt Edge",
    tagline: "Smart devices, fast delivery, clean shopping experience.",
    primaryColor: "#0F4C81",
    secondaryColor: "#56CFE1",
    accentColor: "#111827",
    bgPrimary: "#F3F7FB",
    bgSecondary: "#E9F2FB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#EDF4FB",
    navbarBackground: "#111827",
    footerBackground: "#0F172A",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    textLightColor: "#FFFFFF",
    borderColor: "#CBD5E1",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "High-converting electronics template",
    heroSubtitle: "Built for specs, variants, shipping clarity, and trusted checkout.",
  },
  beauty: {
    mode: "light",
    storeName: "Lune Beauty",
    tagline: "Glow-focused essentials with a refined premium feel.",
    primaryColor: "#C06C84",
    secondaryColor: "#F8B195",
    accentColor: "#355C7D",
    bgPrimary: "#FEF7F8",
    bgSecondary: "#FFF1F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFF4F6",
    navbarBackground: "#2B3752",
    footerBackground: "#1F243A",
    headingColor: "#1F2937",
    bodyTextColor: "#4B5563",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#DC2626",
    infoColor: "#2563EB",
    heroTitle: "Beauty store demo for fast client launch",
    heroSubtitle: "Soft branding, persuasive product storytelling, and polished merchandising.",
  },
  sand: {
    mode: "light",
    storeName: "Sahara Co.",
    tagline: "Warm minimalism. Timeless craft.",
    primaryColor: "#B5835A",
    secondaryColor: "#D4A96A",
    accentColor: "#7C5C3E",
    bgPrimary: "#FAF6F1",
    bgSecondary: "#F3EDE4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F3EE",
    navbarBackground: "#2C1F14",
    footerBackground: "#1E1410",
    headingColor: "#1C1208",
    bodyTextColor: "#3D2B1F",
    mutedTextColor: "#8C7060",
    textLightColor: "#FFFFFF",
    borderColor: "#E2D5C8",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Artisan goods, beautifully presented",
    heroSubtitle: "A warm and grounded store for handcrafted products.",
  },
  forest: {
    mode: "light",
    storeName: "Evergreen",
    tagline: "Earthy tones, natural feel, grounded design.",
    primaryColor: "#2F6B25",
    secondaryColor: "#BDB76B",
    accentColor: "#556B2F",
    bgPrimary: "#F5F5DC",
    bgSecondary: "#F0FFF0",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FAFAF5",
    navbarBackground: "#2F4F4F",
    footerBackground: "#2F4F4F",
    headingColor: "#2F4F4F",
    bodyTextColor: "#3B3C36",
    mutedTextColor: "#808080",
    textLightColor: "#FFFFFF",
    borderColor: "#DCDCDC",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "A natural and grounded storefront",
    heroSubtitle: "Experience a design inspired by the tranquility of the forest.",
  },
  ocean: {
    mode: "light",
    storeName: "Deep Dive",
    tagline: "Cool blues, deep focus, and a fluid experience.",
    primaryColor: "#0077B6",
    secondaryColor: "#90E0EF",
    accentColor: "#023E8A",
    bgPrimary: "#F0F8FF",
    bgSecondary: "#E0F7FA",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F7FDFF",
    navbarBackground: "#023E8A",
    footerBackground: "#03045E",
    headingColor: "#03045E",
    bodyTextColor: "#484848",
    mutedTextColor: "#8E8E8E",
    textLightColor: "#FFFFFF",
    borderColor: "#CAF0F8",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "A fluid and focused shopping experience",
    heroSubtitle: "Dive into a clean, cool, and modern design system.",
  },
  mint: {
    mode: "light",
    storeName: "Fresh Leaf",
    tagline: "Clean. Crisp. Naturally refreshing.",
    primaryColor: "#059669",
    secondaryColor: "#34D399",
    accentColor: "#047857",
    bgPrimary: "#F0FDF4",
    bgSecondary: "#DCFCE7",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F7FEF9",
    navbarBackground: "#064E3B",
    footerBackground: "#022C22",
    headingColor: "#022C22",
    bodyTextColor: "#1F4037",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#BBF7D0",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Organic & wellness products store",
    heroSubtitle: "Fresh branding for health-conscious and eco-friendly brands.",
  },
  royal: {
    mode: "light",
    storeName: "Velvet Crown",
    tagline: "Opulence redefined. Every detail matters.",
    primaryColor: "#7C3AED",
    secondaryColor: "#DDD6FE",
    accentColor: "#5B21B6",
    bgPrimary: "#FAF9FF",
    bgSecondary: "#F3F0FF",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F6FF",
    navbarBackground: "#1E0A3C",
    footerBackground: "#130626",
    headingColor: "#1E0A3C",
    bodyTextColor: "#2E1065",
    mutedTextColor: "#7C6FA0",
    textLightColor: "#FFFFFF",
    borderColor: "#DDD6FE",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#818CF8",
    heroTitle: "Premium jewelry & luxury accessories",
    heroSubtitle: "A regal experience for discerning customers.",
  },
  slate: {
    mode: "light",
    storeName: "Gridline",
    tagline: "Structured. Systematic. Built to convert.",
    primaryColor: "#0EA5E9",
    secondaryColor: "#38BDF8",
    accentColor: "#0284C7",
    bgPrimary: "#F8FAFC",
    bgSecondary: "#F1F5F9",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8FAFC",
    navbarBackground: "#0F172A",
    footerBackground: "#020617",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    textLightColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#0EA5E9",
    heroTitle: "SaaS-inspired clean commerce",
    heroSubtitle: "Precision layout, high trust, and a frictionless checkout.",
  },
  ember: {
    mode: "light",
    storeName: "Ember & Oak",
    tagline: "Rustic warmth meets modern craft.",
    primaryColor: "#C2410C",
    secondaryColor: "#FB923C",
    accentColor: "#9A3412",
    bgPrimary: "#FFFBF7",
    bgSecondary: "#FFF7ED",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FEF3E8",
    navbarBackground: "#1C0A00",
    footerBackground: "#120600",
    headingColor: "#1C0A00",
    bodyTextColor: "#431407",
    mutedTextColor: "#92400E",
    textLightColor: "#FFFFFF",
    borderColor: "#FED7AA",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Handmade goods with a fiery soul",
    heroSubtitle: "Warm tones and bold craft for artisan and food brands.",
  },
  sunset: {
    mode: "light",
    storeName: "Dusk",
    tagline: "Warm hues, vibrant energy, and a memorable impression.",
    primaryColor: "#D95D39",
    secondaryColor: "#F19C79",
    accentColor: "#A84422",
    bgPrimary: "#F7F7F7",
    bgSecondary: "#FFF5F1",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFFBF9",
    navbarBackground: "#2C3E50",
    footerBackground: "#2C3E50",
    headingColor: "#2C3E50",
    bodyTextColor: "#34495E",
    mutedTextColor: "#7F8C8D",
    textLightColor: "#FFFFFF",
    borderColor: "#E0E0E0",
    successColor: "#27AE60",
    warningColor: "#F39C12",
    dangerColor: "#E74C3C",
    infoColor: "#3498DB",
    heroTitle: "A vibrant and energetic storefront",
    heroSubtitle: "Capture the warmth and beauty of a sunset in your design.",
  },
};

export default demoPresets;
