export const demoPresets = {
  fashion: {
    storeName: "Maison Atelier",
    tagline: "Editorial fashion pieces for modern wardrobes.",
    primaryColor: "#7B3F61",
    secondaryColor: "#E9C46A",
    accentColor: "#1F1F1F",
    bgPrimary: "#F7F1F4",
    bgSecondary: "#F5E8EB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F4EDF0",
    navbarBackground: "#1F1F1F",
    footerBackground: "#111111",
    headingColor: "#1F1F1F",
    bodyTextColor: "#3A3A3A",
    mutedTextColor: "#716070",
    borderColor: "#D8C2CF",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Client-ready fashion storefront",
    heroSubtitle: "Elegant storytelling, curated arrivals, and a premium checkout flow.",
  },
  electronics: {
    storeName: "Volt Edge",
    tagline: "Smart devices, fast delivery, clean shopping experience.",
    primaryColor: "#0F4C81",
    secondaryColor: "#56CFE1",
    accentColor: "#111827",
    bgPrimary: "#F3F7FB",
    bgSecondary: "#E9F2FB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#EDF4FB",
    navbarBackground: "#111827",
    footerBackground: "#0F172A",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    borderColor: "#CBD5E1",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "High-converting electronics template",
    heroSubtitle: "Built for specs, variants, shipping clarity, and trusted checkout.",
  },
  beauty: {
    storeName: "Lune Beauty",
    tagline: "Glow-focused essentials with a refined premium feel.",
    primaryColor: "#C06C84",
    secondaryColor: "#F8B195",
    accentColor: "#355C7D",
    bgPrimary: "#FEF7F8",
    bgSecondary: "#FFF1F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFF4F6",
    navbarBackground: "#2B3752",
    footerBackground: "#1F243A",
    headingColor: "#1F2937",
    bodyTextColor: "#4B5563",
    mutedTextColor: "#6B7280",
    borderColor: "#E5E7EB",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#DC2626",
    infoColor: "#2563EB",
    heroTitle: "Beauty store demo for fast client launch",
    heroSubtitle: "Soft branding, persuasive product storytelling, and polished merchandising.",
  },
  forest: {
    storeName: "Evergreen",
    tagline: "Earthy tones, natural feel, grounded design.",
    primaryColor: "#2F6B25",
    secondaryColor: "#BDB76B",
    accentColor: "#556B2F",
    bgPrimary: "#F5F5DC",
    bgSecondary: "#F0FFF0",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FAFAF5",
    navbarBackground: "#2F4F4F",
    footerBackground: "#2F4F4F",
    headingColor: "#2F4F4F",
    bodyTextColor: "#3B3C36",
    mutedTextColor: "#808080",
    borderColor: "#DCDCDC",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "A natural and grounded storefront",
    heroSubtitle: "Experience a design inspired by the tranquility of the forest.",
  },
  ocean: {
    storeName: "Deep Dive",
    tagline: "Cool blues, deep focus, and a fluid experience.",
    primaryColor: "#0077B6",
    secondaryColor: "#90E0EF",
    accentColor: "#023E8A",
    bgPrimary: "#F0F8FF",
    bgSecondary: "#E0F7FA",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F7FDFF",
    navbarBackground: "#023E8A",
    footerBackground: "#03045E",
    headingColor: "#03045E",
    bodyTextColor: "#484848",
    mutedTextColor: "#8E8E8E",
    borderColor: "#CAF0F8",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "A fluid and focused shopping experience",
    heroSubtitle: "Dive into a clean, cool, and modern design system.",
  },
  sunset: {
    storeName: "Dusk",
    tagline: "Warm hues, vibrant energy, and a memorable impression.",
    primaryColor: "#D95D39",
    secondaryColor: "#F19C79",
    accentColor: "#A84422",
    bgPrimary: "#F7F7F7",
    bgSecondary: "#FFF5F1",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFFBF9",
    navbarBackground: "#2C3E50",
    footerBackground: "#2C3E50",
    headingColor: "#2C3E50",
    bodyTextColor: "#34495E",
    mutedTextColor: "#7F8C8D",
    borderColor: "#E0E0E0",
    successColor: "#27AE60",
    warningColor: "#F39C12",
    dangerColor: "#E74C3C",
    infoColor: "#3498DB",
    heroTitle: "A vibrant and energetic storefront",
    heroSubtitle: "Capture the warmth and beauty of a sunset in your design.",
  },
};

export default demoPresets;
