export const demoPresets = {
  // ── DARK ──────────────────────────────────────────────
  midnight: {
    mode: "dark",
    storeName: "Noir Studio",
    tagline: "Bold. Dark. Unapologetically modern.",
    primaryColor: "#6366F1",
    secondaryColor: "#A78BFA",
    accentColor: "#4F46E5",
    bgPrimary: "#0F0F13",
    bgSecondary: "#18181F",
    surfaceColor: "#1E1E28",
    surfaceSoftColor: "#25252F",
    navbarBackground: "#0A0A0F",
    footerBackground: "#0A0A0F",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#2E2E3E",
    successColor: "#34D399",
    warningColor: "#FBBF24",
    dangerColor: "#F87171",
    infoColor: "#60A5FA",
    heroTitle: "Premium dark-mode storefront",
    heroSubtitle: "Sleek, immersive, and built for high-end brands.",
  },
  neon: {
    mode: "dark",
    storeName: "Pulse Drop",
    tagline: "Fast. Loud. Built for the next generation.",
    primaryColor: "#00F5A0",
    secondaryColor: "#00D9F5",
    accentColor: "#7B2FFF",
    bgPrimary: "#080C14",
    bgSecondary: "#0D1220",
    surfaceColor: "#111827",
    surfaceSoftColor: "#161E2E",
    navbarBackground: "#050810",
    footerBackground: "#050810",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#1A2E28",
    successColor: "#00F5A0",
    warningColor: "#FFD60A",
    dangerColor: "#FF4D6D",
    infoColor: "#00D9F5",
    heroTitle: "Next-gen streetwear & tech drops",
    heroSubtitle: "Limited drops. Unlimited hype. Shop before it's gone.",
  },
  obsidian: {
    mode: "dark",
    storeName: "Obsidian",
    tagline: "Sharp edges. Refined taste. Zero compromise.",
    primaryColor: "#E11D48",
    secondaryColor: "#FB7185",
    accentColor: "#BE123C",
    bgPrimary: "#0C0C0C",
    bgSecondary: "#141414",
    surfaceColor: "#1A1A1A",
    surfaceSoftColor: "#202020",
    navbarBackground: "#080808",
    footerBackground: "#080808",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#262626",
    successColor: "#34D399",
    warningColor: "#FBBF24",
    dangerColor: "#F87171",
    infoColor: "#60A5FA",
    heroTitle: "Dark luxury with a bold red accent",
    heroSubtitle: "For brands that demand attention and command respect.",
  },
  cosmic: {
    mode: "dark",
    storeName: "Cosmic",
    tagline: "Explore the universe of flavors.",
    primaryColor: "#A78BFA",
    secondaryColor: "#6366F1",
    accentColor: "#4F46E5",
    bgPrimary: "#111827",
    bgSecondary: "#1F2937",
    surfaceColor: "#374151",
    surfaceSoftColor: "#4B5563",
    navbarBackground: "#0F172A",
    footerBackground: "#0F172A",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#4B5563",
    successColor: "#34D399",
    warningColor: "#FBBF24",
    dangerColor: "#F87171",
    infoColor: "#60A5FA",
    heroTitle: "A taste of the cosmos",
    heroSubtitle: "Discover our new collection of cosmic-themed drinks.",
  },
  crimson: {
    mode: "dark",
    storeName: "Crimson",
    tagline: "For the bold and the brave.",
    primaryColor: "#DC2626",
    secondaryColor: "#F87171",
    accentColor: "#991B1B",
    bgPrimary: "#171717",
    bgSecondary: "#262626",
    surfaceColor: "#404040",
    surfaceSoftColor: "#525252",
    navbarBackground: "#0A0A0A",
    footerBackground: "#0A0A0A",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#525252",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Unleash your inner fire",
    heroSubtitle: "Experience the power of our new crimson collection.",
  },
  emerald: {
    mode: "dark",
    storeName: "Emerald",
    tagline: "Luxury in every detail.",
    primaryColor: "#10B981",
    secondaryColor: "#6EE7B7",
    accentColor: "#059669",
    bgPrimary: "#064E3B",
    bgSecondary: "#047857",
    surfaceColor: "#065F46",
    surfaceSoftColor: "#115E59",
    navbarBackground: "#022C22",
    footerBackground: "#022C22",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#34D399",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "The new standard of luxury",
    heroSubtitle: "Discover our exclusive emerald-themed products.",
  },
  mocha: {
    mode: "dark",
    storeName: "Mocha",
    tagline: "The perfect blend of style and comfort.",
    primaryColor: "#A16207",
    secondaryColor: "#D97706",
    accentColor: "#713F12",
    bgPrimary: "#292524",
    bgSecondary: "#44403C",
    surfaceColor: "#57534E",
    surfaceSoftColor: "#78716C",
    navbarBackground: "#1C1917",
    footerBackground: "#1C1917",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#78716C",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Warm up your style",
    heroSubtitle: "Our new mocha collection is here to keep you cozy.",
  },
  graphite: {
    mode: "dark",
    storeName: "Graphite",
    tagline: "Sleek, modern, and built to last.",
    primaryColor: "#64748B",
    secondaryColor: "#94A3B8",
    accentColor: "#475569",
    bgPrimary: "#1E293B",
    bgSecondary: "#334155",
    surfaceColor: "#475569",
    surfaceSoftColor: "#64748B",
    navbarBackground: "#0F172A",
    footerBackground: "#0F172A",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#64748B",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "The future of design is here",
    heroSubtitle: "Discover our new graphite-themed products.",
  },
  ruby: {
    mode: "dark",
    storeName: "Ruby",
    tagline: "Passion and elegance in every design.",
    primaryColor: "#E11D48",
    secondaryColor: "#F472B6",
    accentColor: "#9F1239",
    bgPrimary: "#1F2937",
    bgSecondary: "#374151",
    surfaceColor: "#4B5563",
    surfaceSoftColor: "#6B7280",
    navbarBackground: "#111827",
    footerBackground: "#111827",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#6B7280",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Ignite your passion",
    heroSubtitle: "Our new ruby collection is here to make a statement.",
  },
  sapphire: {
    mode: "dark",
    storeName: "Sapphire",
    tagline: "Cool, calm, and collected.",
    primaryColor: "#3B82F6",
    secondaryColor: "#60A5FA",
    accentColor: "#2563EB",
    bgPrimary: "#1E3A8A",
    bgSecondary: "#1D4ED8",
    surfaceColor: "#2563EB",
    surfaceSoftColor: "#3B82F6",
    navbarBackground: "#1E40AF",
    footerBackground: "#1E40AF",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#60A5FA",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Dive into the deep blue",
    heroSubtitle: "Discover our new sapphire-themed products.",
  },
  amethyst: {
    mode: "dark",
    storeName: "Amethyst",
    tagline: "Royalty and luxury in every shade.",
    primaryColor: "#9333EA",
    secondaryColor: "#A855F7",
    accentColor: "#7E22CE",
    bgPrimary: "#2E1065",
    bgSecondary: "#4C1D95",
    surfaceColor: "#5B21B6",
    surfaceSoftColor: "#6D28D9",
    navbarBackground: "#1E1B4B",
    footerBackground: "#1E1B4B",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#A78BFA",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "The royal treatment you deserve",
    heroSubtitle: "Our new amethyst collection is here to make you feel like royalty.",
  },
  indigo: {
    mode: "dark",
    storeName: "Indigo",
    tagline: "Deep, mysterious, and full of personality.",
    primaryColor: "#4F46E5",
    secondaryColor: "#6366F1",
    accentColor: "#3730A3",
    bgPrimary: "#312E81",
    bgSecondary: "#4338CA",
    surfaceColor: "#4F46E5",
    surfaceSoftColor: "#6366F1",
    navbarBackground: "#1E1B4B",
    footerBackground: "#1E1B4B",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#818CF8",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Explore the depths of your style",
    heroSubtitle: "Our new indigo collection is here to help you express yourself.",
  },
  jade: {
    mode: "dark",
    storeName: "Jade",
    tagline: "Harmony and balance in every design.",
    primaryColor: "#059669",
    secondaryColor: "#34D399",
    accentColor: "#047857",
    bgPrimary: "#064E3B",
    bgSecondary: "#047857",
    surfaceColor: "#059669",
    surfaceSoftColor: "#10B981",
    navbarBackground: "#022C22",
    footerBackground: "#022C22",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#34D399",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Find your inner peace",
    heroSubtitle: "Our new jade collection is here to bring harmony to your life.",
  },
  garnet: {
    mode: "dark",
    storeName: "Garnet",
    tagline: "Bold, beautiful, and full of life.",
    primaryColor: "#EA580C",
    secondaryColor: "#F97316",
    accentColor: "#C2410C",
    bgPrimary: "#431407",
    bgSecondary: "#7F1D1D",
    surfaceColor: "#991B1B",
    surfaceSoftColor: "#B91C1C",
    navbarBackground: "#450A0A",
    footerBackground: "#450A0A",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#F87171",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Live life in full color",
    heroSubtitle: "Our new garnet collection is here to brighten up your day.",
  },
  onyx: {
    mode: "dark",
    storeName: "Onyx",
    tagline: "The ultimate in sophistication.",
    primaryColor: "#FFFFFF",
    secondaryColor: "#E5E5E5",
    accentColor: "#A3A3A3",
    bgPrimary: "#000000",
    bgSecondary: "#171717",
    surfaceColor: "#262626",
    surfaceSoftColor: "#404040",
    navbarBackground: "#000000",
    footerBackground: "#000000",
    headingColor: "#F9FAFB",
    bodyTextColor: "#E5E7EB",
    mutedTextColor: "#CBD5E1",
    textLightColor: "#FFFFFF",
    borderColor: "#525252",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Simplicity is the ultimate sophistication",
    heroSubtitle: "Discover our new onyx collection.",
  },
  // ── LIGHT ─────────────────────────────────────────────
  ivory: {
    mode: "light",
    storeName: "Blanc Maison",
    tagline: "Pure simplicity. Refined living.",
    primaryColor: "#1A1A1A",
    secondaryColor: "#C9A96E",
    accentColor: "#333333",
    bgPrimary: "#FAFAFA",
    bgSecondary: "#F4F4F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F8F8",
    navbarBackground: "#111111",
    footerBackground: "#0A0A0A",
    headingColor: "#111111",
    bodyTextColor: "#333333",
    mutedTextColor: "#888888",
    textLightColor: "#FFFFFF",
    borderColor: "#E5E5E5",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Luxury home & lifestyle essentials",
    heroSubtitle: "Curated for those who appreciate the beauty of simplicity.",
  },
  fashion: {
    mode: "light",
    storeName: "Maison Atelier",
    tagline: "Editorial fashion pieces for modern wardrobes.",
    primaryColor: "#7B3F61",
    secondaryColor: "#E9C46A",
    accentColor: "#1F1F1F",
    bgPrimary: "#F7F1F4",
    bgSecondary: "#F5E8EB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F4EDF0",
    navbarBackground: "#1F1F1F",
    footerBackground: "#111111",
    headingColor: "#1F1F1F",
    bodyTextColor: "#3A3A3A",
    mutedTextColor: "#716070",
    textLightColor: "#FFFFFF",
    borderColor: "#D8C2CF",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Client-ready fashion storefront",
    heroSubtitle: "Elegant storytelling, curated arrivals, and a premium checkout flow.",
  },
  electronics: {
    mode: "light",
    storeName: "Volt Edge",
    tagline: "Smart devices, fast delivery, clean shopping experience.",
    primaryColor: "#0F4C81",
    secondaryColor: "#56CFE1",
    accentColor: "#111827",
    bgPrimary: "#F3F7FB",
    bgSecondary: "#E9F2FB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#EDF4FB",
    navbarBackground: "#111827",
    footerBackground: "#0F172A",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    textLightColor: "#FFFFFF",
    borderColor: "#CBD5E1",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "High-converting electronics template",
    heroSubtitle: "Built for specs, variants, shipping clarity, and trusted checkout.",
  },
  beauty: {
    mode: "light",
    storeName: "Lune Beauty",
    tagline: "Glow-focused essentials with a refined premium feel.",
    primaryColor: "#C06C84",
    secondaryColor: "#F8B195",
    accentColor: "#355C7D",
    bgPrimary: "#FEF7F8",
    bgSecondary: "#FFF1F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFF4F6",
    navbarBackground: "#2B3752",
    footerBackground: "#1F243A",
    headingColor: "#1F2937",
    bodyTextColor: "#4B5563",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#DC2626",
    infoColor: "#2563EB",
    heroTitle: "Beauty store demo for fast client launch",
    heroSubtitle: "Soft branding, persuasive product storytelling, and polished merchandising.",
  },
  sand: {
    mode: "light",
    storeName: "Sahara Co.",
    tagline: "Warm minimalism. Timeless craft.",
    primaryColor: "#B5835A",
    secondaryColor: "#D4A96A",
    accentColor: "#7C5C3E",
    bgPrimary: "#FAF6F1",
    bgSecondary: "#F3EDE4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F3EE",
    navbarBackground: "#2C1F14",
    footerBackground: "#1E1410",
    headingColor: "#1C1208",
    bodyTextColor: "#3D2B1F",
    mutedTextColor: "#8C7060",
    textLightColor: "#FFFFFF",
    borderColor: "#E2D5C8",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Artisan goods, beautifully presented",
    heroSubtitle: "A warm and grounded store for handcrafted products.",
  },
  forest: {
    mode: "light",
    storeName: "Evergreen",
    tagline: "Earthy tones, natural feel, grounded design.",
    primaryColor: "#2F6B25",
    secondaryColor: "#BDB76B",
    accentColor: "#556B2F",
    bgPrimary: "#F5F5DC",
    bgSecondary: "#F0FFF0",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FAFAF5",
    navbarBackground: "#2F4F4F",
    footerBackground: "#2F4F4F",
    headingColor: "#2F4F4F",
    bodyTextColor: "#3B3C36",
    mutedTextColor: "#808080",
    textLightColor: "#FFFFFF",
    borderColor: "#DCDCDC",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "A natural and grounded storefront",
    heroSubtitle: "Experience a design inspired by the tranquility of the forest.",
  },
  ocean: {
    mode: "light",
    storeName: "Deep Dive",
    tagline: "Cool blues, deep focus, and a fluid experience.",
    primaryColor: "#0077B6",
    secondaryColor: "#90E0EF",
    accentColor: "#023E8A",
    bgPrimary: "#F0F8FF",
    bgSecondary: "#E0F7FA",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F7FDFF",
    navbarBackground: "#023E8A",
    footerBackground: "#03045E",
    headingColor: "#03045E",
    bodyTextColor: "#484848",
    mutedTextColor: "#8E8E8E",
    textLightColor: "#FFFFFF",
    borderColor: "#CAF0F8",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "A fluid and focused shopping experience",
    heroSubtitle: "Dive into a clean, cool, and modern design system.",
  },
  mint: {
    mode: "light",
    storeName: "Fresh Leaf",
    tagline: "Clean. Crisp. Naturally refreshing.",
    primaryColor: "#059669",
    secondaryColor: "#34D399",
    accentColor: "#047857",
    bgPrimary: "#F0FDF4",
    bgSecondary: "#DCFCE7",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F7FEF9",
    navbarBackground: "#064E3B",
    footerBackground: "#022C22",
    headingColor: "#022C22",
    bodyTextColor: "#1F4037",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#BBF7D0",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Organic & wellness products store",
    heroSubtitle: "Fresh branding for health-conscious and eco-friendly brands.",
  },
  royal: {
    mode: "light",
    storeName: "Velvet Crown",
    tagline: "Opulence redefined. Every detail matters.",
    primaryColor: "#7C3AED",
    secondaryColor: "#DDD6FE",
    accentColor: "#5B21B6",
    bgPrimary: "#FAF9FF",
    bgSecondary: "#F3F0FF",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8F6FF",
    navbarBackground: "#1E0A3C",
    footerBackground: "#130626",
    headingColor: "#1E0A3C",
    bodyTextColor: "#2E1065",
    mutedTextColor: "#7C6FA0",
    textLightColor: "#FFFFFF",
    borderColor: "#DDD6FE",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#818CF8",
    heroTitle: "Premium jewelry & luxury accessories",
    heroSubtitle: "A regal experience for discerning customers.",
  },
  slate: {
    mode: "light",
    storeName: "Gridline",
    tagline: "Structured. Systematic. Built to convert.",
    primaryColor: "#0EA5E9",
    secondaryColor: "#38BDF8",
    accentColor: "#0284C7",
    bgPrimary: "#F8FAFC",
    bgSecondary: "#F1F5F9",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F8FAFC",
    navbarBackground: "#0F172A",
    footerBackground: "#020617",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    textLightColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#0EA5E9",
    heroTitle: "SaaS-inspired clean commerce",
    heroSubtitle: "Precision layout, high trust, and a frictionless checkout.",
  },
  ember: {
    mode: "light",
    storeName: "Ember & Oak",
    tagline: "Rustic warmth meets modern craft.",
    primaryColor: "#C2410C",
    secondaryColor: "#FB923C",
    accentColor: "#9A3412",
    bgPrimary: "#FFFBF7",
    bgSecondary: "#FFF7ED",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FEF3E8",
    navbarBackground: "#1C0A00",
    footerBackground: "#120600",
    headingColor: "#1C0A00",
    bodyTextColor: "#431407",
    mutedTextColor: "#92400E",
    textLightColor: "#FFFFFF",
    borderColor: "#FED7AA",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Handmade goods with a fiery soul",
    heroSubtitle: "Warm tones and bold craft for artisan and food brands.",
  },
  sunset: {
    mode: "light",
    storeName: "Dusk",
    tagline: "Warm hues, vibrant energy, and a memorable impression.",
    primaryColor: "#D95D39",
    secondaryColor: "#F19C79",
    accentColor: "#A84422",
    bgPrimary: "#F7F7F7",
    bgSecondary: "#FFF5F1",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFFBF9",
    navbarBackground: "#2C3E50",
    footerBackground: "#2C3E50",
    headingColor: "#2C3E50",
    bodyTextColor: "#34495E",
    mutedTextColor: "#7F8C8D",
    textLightColor: "#FFFFFF",
    borderColor: "#E0E0E0",
    successColor: "#27AE60",
    warningColor: "#F39C12",
    dangerColor: "#E74C3C",
    infoColor: "#3498DB",
    heroTitle: "A vibrant and energetic storefront",
    heroSubtitle: "Capture the warmth and beauty of a sunset in your design.",
  },
  azure: {
    mode: "light",
    storeName: "Azure",
    tagline: "Clean, fresh, and full of life.",
    primaryColor: "#3B82F6",
    secondaryColor: "#60A5FA",
    accentColor: "#2563EB",
    bgPrimary: "#EFF6FF",
    bgSecondary: "#DBEAFE",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F0F9FF",
    navbarBackground: "#1E40AF",
    footerBackground: "#1C3D9A",
    headingColor: "#1E3A8A",
    bodyTextColor: "#1E293B",
    mutedTextColor: "#475569",
    textLightColor: "#FFFFFF",
    borderColor: "#BFDBFE",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "A breath of fresh air",
    heroSubtitle: "Our new azure collection is here to brighten up your day.",
  },
  citrus: {
    mode: "light",
    storeName: "Citrus",
    tagline: "Zesty, vibrant, and full of energy.",
    primaryColor: "#F59E0B",
    secondaryColor: "#FBBF24",
    accentColor: "#D97706",
    bgPrimary: "#FFFBEB",
    bgSecondary: "#FEF3C7",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFFDE7",
    navbarBackground: "#B45309",
    footerBackground: "#92400E",
    headingColor: "#92400E",
    bodyTextColor: "#374151",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#FDE68A",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Add a little zest to your life",
    heroSubtitle: "Our new citrus collection is here to energize you.",
  },
  sakura: {
    mode: "light",
    storeName: "Sakura",
    tagline: "Delicate, beautiful, and full of grace.",
    primaryColor: "#F472B6",
    secondaryColor: "#F9A8D4",
    accentColor: "#EC4899",
    bgPrimary: "#FEF6F9",
    bgSecondary: "#FCE7F3",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFF0F5",
    navbarBackground: "#9D174D",
    footerBackground: "#831843",
    headingColor: "#831843",
    bodyTextColor: "#374151",
    mutedTextColor: "#6B7280",
    textLightColor: "#FFFFFF",
    borderColor: "#FBCFE8",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Experience the beauty of spring",
    heroSubtitle: "Our new sakura collection is here to bring a touch of elegance to your life.",
  },
};

export default demoPresets;