name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # كل 10 دقايق
  workflow_dispatch:  # يخليك تشغله يدوياً للتجربة

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://your-service-name.onrender.com
